name: uuid4s
baseurl: /uuid4s
description: Purely functional UUID's for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.4+7-05419ec3-SNAPSHOT
org: org.pure4s
markdown: kramdown
