name: uuid4s
baseurl: /uuid4s
description: Functional UUID's for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 98036376+20190115-2035-SNAPSHOT
org: com.typepure
markdown: kramdown
