name: uuid4s
baseurl: /uuid4s
description: Purely functional UUID's for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.3+3-08d55f9c+20190128-1959-SNAPSHOT
org: org.pure4s
markdown: kramdown
