name: uuid4s
baseurl: /uuid4s
description: Functional UUID's for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 256fcfde-SNAPSHOT
org: io.github.typepure
markdown: kramdown
