name: uuid4s
baseurl: /uuid4s
description: Purely functional UUID's for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.3+6-f810c4a5-SNAPSHOT
org: org.pure4s
markdown: kramdown
