name: uuid4s
baseurl: /uuid4s
description: Purely functional UUID's for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.2+4-e4174b7e+20190126-1543-SNAPSHOT
org: org.pure4s
markdown: kramdown
