name: uuid4s
baseurl: /uuid4s
description: Purely functional UUID's for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.5+1-afc7d4fe-SNAPSHOT
org: org.pure4s
markdown: kramdown
