name: uuid4s
baseurl: /uuid4s
description: Functional UUID's for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 3ee23a93+20190116-2202-SNAPSHOT
org: io.github.typepure
markdown: kramdown
