name: uuid4s
baseurl: /uuid4s
description: Functional UUID's for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.0+2-cc0501ac+20190123-1741-SNAPSHOT
org: org.pure4s
markdown: kramdown
