name: uuid4s
baseurl: /uuid4s
description: Functional UUID's for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: a4a552c1+20190115-2200-SNAPSHOT
org: io.github.typepure
markdown: kramdown
